[package]
name = "nesemu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nesemu-cpu = { path = "../cpu" , package="nesemu-cpu" }
nesemu-gui = { path = "../gui" , package="nesemu-gui" }