[package]
name = "nesemu"
version = "0.1.0"
edition = "2021"

[dependencies]
nesemu-cpu = { path = "../cpu" , package="nesemu-cpu" }
nesemu-gui = { path = "../gui" , package="nesemu-gui" }
nesemu-core = { path = "../core" , package="nesemu-core" }
