[package]
name = "nesemu_cpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nesemu-core = { path = "../core" , package="nesemu_core" }
serde = { version = "1.0.188", features = ["derive"] }
